export default [
    {
        idx: 1,
        gname: "반스케주얼",
        category: "undefined",
        gprice: "55000",
    },
    {
        idx: 2,
        gname: "반스어얼리",
        category: "women",
        gprice: "46000",
    },
    {
        idx: 3,
        gname: "반스뉴진스",
        category: "women",
        gprice: "20000",
    },
    {
        idx: 4,
        gname: "반스케주얼",
        category: "man",
        gprice: "20000",
    },
    {
        idx: 5,
        gname: "반스뉴진스",
        category: "women",
        gprice: "46000",
    },
    {
        idx: 6,
        gname: "반스스타일",
        category: "women",
        gprice: "66000",
    },
    {
        idx: 7,
        gname: "반스스타일",
        category: "man",
        gprice: "20000",
    },
    {
        idx: 8,
        gname: "반스케주얼",
        category: "undefined",
        gprice: "25000",
    },
    {
        idx: 9,
        gname: "반스스타일",
        category: "women",
        gprice: "20000",
    },
    {
        idx: 10,
        gname: "반스케주얼",
        category: "women",
        gprice: "46000",
    },
    {
        idx: 11,
        gname: "반스어얼리",
        category: "women",
        gprice: "20000",
    },
    {
        idx: 12,
        gname: "반스뉴진스",
        category: "man",
        gprice: "66000",
    },
    {
        idx: 13,
        gname: "반스스타일",
        category: "undefined",
        gprice: "66000",
    },
    {
        idx: 14,
        gname: "반스뉴진스",
        category: "undefined",
        gprice: "25000",
    },
    {
        idx: 15,
        gname: "반스뉴진스",
        category: "man",
        gprice: "25000",
    },
    {
        idx: 16,
        gname: "반스뉴진스",
        category: "women",
        gprice: "66000",
    },
    {
        idx: 17,
        gname: "반스어얼리",
        category: "man",
        gprice: "25000",
    },
    {
        idx: 18,
        gname: "반스뉴진스",
        category: "undefined",
        gprice: "25000",
    },
    {
        idx: 19,
        gname: "반스스타일",
        category: "man",
        gprice: "55000",
    },
];

